### ISSUE TITLE
Amplify Gen 2 x Monorepo

### ISSUE THREAD

**Issue by danny-yamamoto** [danny-yamamoto/roughsketch#55]

**Comment by danny-yamamoto** [comment]
```bash
root ➜ /workspaces/kbp-bpaas-fdby (BPD-168) $ npx ampx pipeline-deploy --branch $BRANCH_NAME --app-id $AMPLIFY_APP_ID --debug -w ./api

ampx pipeline-deploy

Command to deploy backends in a custom CI/CD pipeline. This command is not inten
ded to be used locally.

Options:
  --debug            Print debug logs to the console  [boolean] [default: false]
  --help             Show help                                         [boolean]
  --branch           Name of the git branch being deployed   [string] [required]
  --app-id           The app id of the target Amplify app    [string] [required]
  --outputs-out-dir  A path to directory where amplify_outputs is written. If no
                     t provided defaults to current process working directory.
                                                                        [string]
  --outputs-version  Version of the configuration. Version 0 represents classic
                     amplify-cli config file amplify-configuration and 1 represe
                     nts newer config file amplify_outputs
                                     [string] [choices: "0", "1"] [default: "1"]

Unknown argument: w
[DEBUG] 2024-06-27T01:32:51.776Z: Failed to emit usage metrics
[DEBUG] 2024-06-27T01:32:51.776Z: Error: Region is missing
[DEBUG] 2024-06-27T01:32:51.776Z: Error: Region is missing
    at default (/workspaces/kbp-bpaas-fdby/node_modules/@smithy/config-resolver/dist-cjs/index.js:117:11)
    at /workspaces/kbp-bpaas-fdby/node_modules/@aws-sdk/client-sts/node_modules/@smithy/node-config-provider/dist-cjs/index.js:90:104
    at /workspaces/kbp-bpaas-fdby/node_modules/@smithy/property-provider/dist-cjs/index.js:97:33
[DEBUG] 2024-06-27T01:32:51.776Z: Error: Region is missing
root ➜ /workspaces/kbp-bpaas-fdby (BPD-168) $
```
